- name: Update a10_slb_template_policy_forward_policy_source example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_policy_forward_policy_source instance
    a10_slb_template_policy_forward_policy_source:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      policy_name: "{{ policy_name }}"
      state: present
      name: my_source
