- name: Delete a10_slb_template_dynamic_service example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_dynamic_service instance
    a10_slb_template_dynamic_service:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: absent
      name: my_dynamic-service
